[package]
edition = "2021"
name = "famicom_emulator"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.0"
lazy_static = "1.4"

sdl2 = "0.35"
rand = "0.8"
